# Numpy - Numerical Python

list is slow as it can take all kinf of data types in same list , so it conitnuously check the data types and slows the system

## Nd-Array
N dimensional array.


In [2]:
arr=[1,2,3]
print(arr*5)

arr=[x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
import numpy as np
arr=np.array(arr)
print(arr.dtype)

arr1=np.array([1.2,3.4,6.5])
print(arr1.dtype)

int64
float64


In [4]:
# integer into float it is called upcasting
arr=np.array([1,2,3.2])
print(arr.dtype)
# upcasting to string
arr2=np.array([1,2,3,"hello"])
print(arr2.dtype)

float64
<U21


## Fixing the dimension of the array 


In [46]:
arr=np.array([1,2,3])
print(arr)
print(arr.ndim)
print(arr.dtype)

[1 2 3]
1
int64


## Accessing multiple dimension array

In [49]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,:])

20
[40 50 60]


## Selecting a data type for an array

In [7]:
arr=np.array([1,2,3], dtype=np.int8)

In [8]:
arr3=np.array([1,2,3,'zuthi', True])
print(type(arr3))
print(arr3.dtype)

<class 'numpy.ndarray'>
<U21


In [9]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64


In [10]:
# let's try with tuple
tup=(1,2,3)
arr=np.array(tup)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)


[1 2 3]
<class 'numpy.ndarray'>
int64
1


In [12]:
# let's try with set
st={1,2,3}
arr=np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

# here set is taken as object , so the data type can not be changed
#  so first change it to list and then to array
st={1,2,3}
arr=np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)


{1, 2, 3}
<class 'numpy.ndarray'>
object
0
[1 2 3]
<class 'numpy.ndarray'>
int64
1


In [13]:
# let's try with dictionary
d={1:"one", 2:"two", 3:"three"}
key=d.keys()
values=d.values()
items=d.items()
arr=np.array(items)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim) 

dict_items([(1, 'one'), (2, 'two'), (3, 'three')])
<class 'numpy.ndarray'>
object
0


## Creating random values

In [ ]:
r=np.random.rand(2,3)
# 0 to 1 float value
arr=np.array(r)
print(arr)
print(type(arr))        
print(arr.dtype)
print(arr.ndim)

[[0.54095718 0.47905998 0.70019149]
 [0.81809332 0.23777877 0.59100445]]
<class 'numpy.ndarray'>
float64
2


In [16]:
r=np.random.randint(1,10,(2,3))
# 0 to 1 float value
arr=np.array(r)
print(arr)
print(type(arr))        
print(arr.dtype)
print(arr.ndim)

[[7 7 1]
 [5 8 8]]
<class 'numpy.ndarray'>
int32
2


In [17]:
# to generate floating value

r=np.random.uniform(1,10,(2,3))
# 0 to 1 float value
arr=np.array(r)
print(arr)
print(type(arr))        
print(arr.dtype)
print(arr.ndim)


[[7.26393347 6.98751119 1.98014533]
 [4.31447694 4.46176039 9.30796013]]
<class 'numpy.ndarray'>
float64
2


## array creating with range

In [18]:
# np.arrange(first,end, step) 
arr = np.arange(1,10,2)
print(arr)
print(type(arr))
print(arr.dtype)

[1 3 5 7 9]
<class 'numpy.ndarray'>
int64


In [20]:
arr=np.arange(1,10,1).reshape(3,3)
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [ ]:
# np.linespace(start,stop(included),koita)

arr = np.linspace(1,10,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>
float64
1


In [22]:
# np.logspace(start,stop(included),koita)

arr=np.logspace(0,4,5)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
<class 'numpy.ndarray'>
float64
1


In [24]:
# np.logspace(start,stop(included),koita)

arr=np.logspace(0,4,6,base=2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
1


## getting a column or row

In [27]:
arr=[1,2,3,4,5,6,7,8,9]
arr=np.array(arr).reshape(3,3)
print(arr)
print(type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64


In [28]:
col_0=arr[:,0:1]
print(col_0)

[[1]
 [4]
 [7]]


In [29]:
row_0=arr[0:1,:]
print(row_0)

[[1 2 3]]


In [30]:
portion=arr[::,0:2]
print(portion)

[[1 2]
 [4 5]
 [7 8]]


In [36]:
arr=[1,2,3,4,5,6,7,8,9]
arr=np.array(arr)
arr1=arr[0:5]
# here in this way the array is not getting copied just indexing is happening
#  so if any changes brought in arr1 it will also reflect in arr
print(arr1)
arr1[0]=100
print(arr1)
print(arr)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5   6   7   8   9]


In [38]:
arr_copy=arr[1:5].copy()
print(arr_copy)
arr_copy[0]=200
print(arr_copy)
print(arr1)


[2 3 4 5]
[200   3   4   5]
[100   2   3   4   5]


## Advanced Indexing

In [41]:
lst=np.array([1,2,3,4,5])
values=lst[[2,4]]
print(values)

[3 5]


In [44]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[[0,1],[1,2]])
print(arr[arr<2])

arr[arr<3]=0
print(arr)

[2 6]
[1]
[[0 0 3]
 [4 5 6]]
