In [18]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5))
arr.shape

(10, 5)

In [19]:
arr

array([[19, 75,  2, 24, 77],
       [44, 53, 85, 15, 19],
       [86, 76,  1, 39, 61],
       [78,  4, 84, 39, 65],
       [31, 80, 79, 35, 91],
       [ 8, 66, 44, 38, 99],
       [82, 42, 18, 89, 78],
       [33, 30, 47, 32, 90],
       [57, 91, 55, 94, 50],
       [53, 55, 39, 14, 88]], dtype=int32)

In [20]:
b=arr.reshape(5,10)
b

array([[19, 75,  2, 24, 77, 44, 53, 85, 15, 19],
       [86, 76,  1, 39, 61, 78,  4, 84, 39, 65],
       [31, 80, 79, 35, 91,  8, 66, 44, 38, 99],
       [82, 42, 18, 89, 78, 33, 30, 47, 32, 90],
       [57, 91, 55, 94, 50, 53, 55, 39, 14, 88]], dtype=int32)

In [21]:
b.ndim

2

In [22]:
flaten=b.flatten()
flaten.ndim
flaten

array([19, 75,  2, 24, 77, 44, 53, 85, 15, 19, 86, 76,  1, 39, 61, 78,  4,
       84, 39, 65, 31, 80, 79, 35, 91,  8, 66, 44, 38, 99, 82, 42, 18, 89,
       78, 33, 30, 47, 32, 90, 57, 91, 55, 94, 50, 53, 55, 39, 14, 88],
      dtype=int32)

In [23]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(20,30,size=(2,3))

In [24]:
a

array([[9, 9, 6],
       [9, 5, 4]], dtype=int32)

In [25]:
b

array([[22, 23, 20],
       [20, 23, 23]], dtype=int32)

In [26]:
con_row=np.concatenate((a,b),axis=0)
# row wise concatenate
con_row
# row wise needs he row same but column can be different

array([[ 9,  9,  6],
       [ 9,  5,  4],
       [22, 23, 20],
       [20, 23, 23]], dtype=int32)

In [27]:
con_row=np.concatenate((a,b),axis=1)
# column wise concatenate
con_row
# column wise needs he column same but row can be different

array([[ 9,  9,  6, 22, 23, 20],
       [ 9,  5,  4, 20, 23, 23]], dtype=int32)

In [28]:
# error
x=np.random.randint(1,10,size=(2,3))
y=np.random.randint(20,30,size=(1,3))
con_row=np.concatenate((x,y),axis=0)
con_row

array([[ 2,  9,  6],
       [ 6,  7,  8],
       [26, 22, 29]], dtype=int32)

## Tranpose Matrix

In [29]:
arry=np.array([[1,2,3],[4,5,6]])
arr=arry.T
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

## Split Dataset

### array_split for non equal split, split for equal split

In [30]:
a=np.random.randint(1,10,size=(2,3))
print(a)
splitted_array=np.array_split(a,3)
print(splitted_array)
splitted_array=np.split(a,2)
print(splitted_array)

[[9 5 5]
 [7 6 1]]
[array([[9, 5, 5]], dtype=int32), array([[7, 6, 1]], dtype=int32), array([], shape=(0, 3), dtype=int32)]
[array([[9, 5, 5]], dtype=int32), array([[7, 6, 1]], dtype=int32)]


### Arithmatic Operations

In [31]:
x=np.array([20,30,40,50])
y=np.array([2,3,4,5])

mul=x*y
print(mul)

div=x/y
print(div)

add=x+y
print(add)

sub=x-y
print(sub)

remainder=x%y
print(remainder)



[ 40  90 160 250]
[10. 10. 10. 10.]
[22 33 44 55]
[18 27 36 45]
[0 0 0 0]


In [32]:
sin_val=np.sin(x)
sin_val

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [33]:
cos_val=np.cos(x)
cos_val

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [34]:
deg_con=np.rad2deg(x)
deg_con

array([1145.91559026, 1718.87338539, 2291.83118052, 2864.78897565])

In [35]:
Base_10_log=np.log10(x)
Base_10_log

array([1.30103   , 1.47712125, 1.60205999, 1.69897   ])

In [36]:
sqrt=np.sqrt(x)
sqrt

array([4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [37]:
s=np.sum(x)
s
sum=np.cumulative_sum(x)
sum

array([ 20,  50,  90, 140])

## Comparison

In [38]:
x=np.array([1,2,3,4,5])
y=np.array([5,4,3,2,1])

greater=x>y
print(greater)

equal=x==y
print(equal)

print(np.all(greater))
print(np.any(greater))

[False False False  True  True]
[False False  True False False]
False
True


##  Sorting

In [39]:
z=y.copy()
z

array([5, 4, 3, 2, 1])

In [40]:
z.sort()
z

array([1, 2, 3, 4, 5])

In [41]:
mat=np.array([[4,1,6],[9,2,3],[7,3,9]])
# horizon sort
hor_sort=np.sort(mat,axis=1)
print(hor_sort)
# vertical sort
ver_sort=np.sort(mat,axis=0)
print(ver_sort)

[[1 4 6]
 [2 3 9]
 [3 7 9]]
[[4 1 3]
 [7 2 6]
 [9 3 9]]


## Searching

In [42]:
index=np.where(mat>3)
index

(array([0, 0, 1, 2, 2]), array([0, 2, 0, 0, 2]))

In [43]:
index=np.where(mat>3,mat,0)
index

array([[4, 0, 6],
       [9, 0, 0],
       [7, 0, 9]])

In [44]:
max_index=np.argmax(mat)
max_index

np.int64(3)

In [45]:
min_index=np.argmin(mat)
min_index

np.int64(1)

## counting

In [46]:
val_great_6=np.count_nonzero(mat>=6)
val_great_6

np.int64(4)

In [47]:
uni=np.unique(mat)
uni

array([1, 2, 3, 4, 6, 7, 9])

In [48]:
uni,count=np.unique(mat,return_counts=True)
print(uni)
print(count)

[1 2 3 4 6 7 9]
[1 1 2 1 1 1 2]


## Statistical methods

In [49]:
dataset=np.genfromtxt('../media/test.csv',delimiter=',',skip_header=1)
dataset

array([[82., 15.],
       [ 4., 95.],
       [36., 32.],
       [29., 18.],
       [95., 14.],
       [87., 95.],
       [70., 12.],
       [76., 55.],
       [ 5.,  4.],
       [12., 28.],
       [30., 65.],
       [78.,  4.],
       [72., 26.],
       [92., 84.],
       [90., 70.],
       [54., 29.],
       [58., 76.],
       [36.,  1.],
       [98., 21.],
       [90., 55.]])

In [50]:
sample=dataset[:,:1]
sample

array([[82.],
       [ 4.],
       [36.],
       [29.],
       [95.],
       [87.],
       [70.],
       [76.],
       [ 5.],
       [12.],
       [30.],
       [78.],
       [72.],
       [92.],
       [90.],
       [54.],
       [58.],
       [36.],
       [98.],
       [90.]])

In [51]:
sample.T

array([[82.,  4., 36., 29., 95., 87., 70., 76.,  5., 12., 30., 78., 72.,
        92., 90., 54., 58., 36., 98., 90.]])

In [52]:
np.max(sample)


np.float64(98.0)

In [53]:
np.min(sample)

np.float64(4.0)

In [54]:
np.mean(sample)

np.float64(59.7)

In [55]:
np.median(sample)

np.float64(71.0)

In [56]:
np.std(sample)

np.float64(30.85952041104981)

In [57]:
study_hours=np.array([2,3,4,5,6])
exam_scores=np.array([50,60,70,80,90])

data=np.array([study_hours,exam_scores])

correlation=np.corrcoef(study_hours,exam_scores)
print(correlation)

[[1. 1.]
 [1. 1.]]


## Linear Algebra

In [58]:
dot_product=np.dot(study_hours,exam_scores)
print(dot_product)

1500


In [59]:
# diagnal summation is trace
np.trace(mat)

np.int64(15)

In [62]:
# deterinate of a matrix
sq_matrix=np.array([[1,2],[3,4]])
det=np.linalg.det(sq_matrix)
det

np.float64(-2.0000000000000004)

In [64]:
# get rank of a matrix
rank=np.linalg.matrix_rank(sq_matrix)
rank

np.int64(2)